- name: apt-transport
  apt:
    name: apt-transport-https

# TODO: convert to correct ansible module
#
- name: setup elastic repo
  shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
    echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-6.x.list

- name: apt-get update
  apt:
    update_cache: yes

- name: curl
  apt:
    name: curl

- name: java
  apt:
    name: default-jre

# for discovery
#
- name: avahi-daemon
  apt:
    name: avahi-daemon
- name: libnss-mdns
  apt:
    name: libnss-mdns

- name: include filebeat
  include: filebeat.yml
